### ISSUE TITLE
[ZH][BUG]点击view mind map之后, 渲染成功后，mind map迅速消失，黑屏

### ISSUE THREAD

**Issue by loverubywithout** [baobao1270/vscode-markdown-mindmap-preview#8]
**提交前检查单**
 - 您是否已检索已有的 issue 并尝试解决问题？『是』
 - 您是否已详阅文档与 README 中的『已知错误』？『是』
 - 您是否已将 VSCode 与本插件更新至最新稳定版本？『是』
 - 您的操作系统名称和版本：『Windows_NT x64 10.0.19042』
 - 您的 VSCode 版本：『1.53.2 (user setup)』
 - 您的 `vscode-markdown-mindmap-preview` 插件版本：『1.1.0』
 - 请尽量使用『全角空心引号』以保持格式一致，谢谢！『好的，我会遵守』

**重现步骤**
 1. 点击view mind map之后，会弹出Mind Map Preview, 渲染成功之后，mind map迅速消失，黑屏；
 2. 当我切换不同应用的时候，比如我点击桌面或者浏览器，再点击回vscode的时候；
 2.1. 有时候会出现rendering，please wait；
 2.2. 有时候会出现半张mind map, 点击节点能展开和折叠，但是鼠标滚动和左键拖拽无反应

**期望行为**

请简述您期望的程序行为『可选』（此行可删除）

**截图**
对应到2.2.的情况，出现半张mind map, 点击节点有效，但是鼠标滚动和左键拖拽无反应
![image](https://user-images.githubusercontent.com/64020923/108580326-06085580-7366-11eb-9091-b002aa358598.png)

『可选』（此行可删除）

**日志**

请使用 `Ctrl+Shift+I` 快捷键打开调试控制台，将有关的日志粘贴在下方：
```
  ERR Cannot read property 'document' of undefined: TypeError: Cannot read property 'document' of undefined
	at f (c:\Users\kite\.vscode\extensions\yzhang.markdown-all-in-one-3.4.0\dist\extension.js:1:296467)
	at p (c:\Users\kite\.vscode\extensions\yzhang.markdown-all-in-one-3.4.0\dist\extension.js:1:293567)
	at g (c:\Users\kite\.vscode\extensions\yzhang.markdown-all-in-one-3.4.0\dist\extension.js:1:295259)
	at v.provideCodeLenses (c:\Users\kite\.vscode\extensions\yzhang.markdown-all-in-one-3.4.0\dist\extension.js:1:298023)
	at l.provideCodeLenses (d:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:138899)
	at d:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:161293
	at we._withAdapter (d:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:159898)
	at we.$provideCodeLenses (d:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:161271)
	at p._doInvokeHandler (d:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:10276)
	at p._invokeHandler (d:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:9968)
	at p._receiveRequest (d:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:8587)
	at p._receiveOneMessage (d:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:7440)
	at d:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:89:5568
	at v.fire (d:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55:1836)
	at d.fire (d:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:15515)
	at d:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:29104
	at v.fire (d:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55:1836)
	at d.fire (d:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:15515)
	at t._receiveMessage (d:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:20765)
	at d:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:17659
	at v.fire (d:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55:1836)
	at u.acceptChunk (d:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:12880)
	at d:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:63:12228
	at Socket.m (d:\ProgramData\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:104:12375)
	at Socket.emit (events.js:315:20)
	at addChunk (_stream_readable.js:295:12)
	at readableAddChunk (_stream_readable.js:271:9)
	at Socket.Readable.push (_stream_readable.js:212:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

请使用 `Ctrl+Shift+P` 打开命令栏，并输入命令 `>developer: open webview developer tools`，将有关的日志粘贴在下方：

![image](https://user-images.githubusercontent.com/64020923/108580546-e291da80-7366-11eb-8348-1c1aa61b99e0.png)

**Comment by loverubywithout** [comment]
尝试过重启vscode, disable和enable，都无果，而且最奇怪的是，我昨天用的好好的，今天早上一打开，没有对vscode做任何其他操作，就出现这种情况了

**Comment by baobao1270** [comment]
抱歉，最近忙着考研，本项目暂时没有精力维护了。如果未来有机会，可能会继续维护，并进行重构。感谢您的支持。 #9
